language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run build
  # - npm run server &
  # - npm install puppeteer
  # - npx percy exec -- node test/snapshots.js
